name: GalaxyGraves
version: '1.0'
main: co.mcGalaxy.galaxyGraves.GalaxyGraves
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  Graves:
    permission: GalaxyGraves.Command.Grave
    description: Main plugin command
    aliases:
      - grave
